package libtiff.example.callmebackapp;

/**
 * Created by Antonis on 8/7/2016.
 */
public class Android {
    static String[] code = new String[]
            {
                    "Albania (Vodafone)",
                    "Australia (Telstra)",
                    "Bangladesh (AirTel)",
                    "Bangladesh (Banglalink)",
                    "Bangladesh (Grameenphone)",
                    "Bulgaria (Telenor)",
                    "Belarus (Life)",
                    "Belgium (Proximus)",
                    "Brazil (DigiCell)",
                    "Cameroon (Orange)",
                    "Cyprus (CallSat)",
                    "Cyprus (Cyta)",
                    "Cyprus (MTN)",
                    "Cyprus (PrimeTel)",
                    "Docomo (Tata Docomo)",
                    "Egypt (Etisalat)",
                    "Greece (Vodafone CU)",
                    "India (AirTel)",
                    "India (AirCel)",
                    "India (Vodafone)",
                    "Iraq (Korektel)",
                    "Jamaica (Flow)",
                    "Jordan (Zain Jordan)",
                    "Kenya (SafariCom)",
                    "Kenya (YUMobile)",
                    "Maldives (Dhiraagu)",
                    "Montenegro (TMobile)",
                    "New Zealand (Skinny Mobile)",
                    "Nigeria (AirTel)",
                    "Nigeria (Etilasat)",
                    "Nigeria (MTN)",
                    "Nigeria (Glo)",
                    "Oman (FriendiMobile)",
                    "Oman (RennaMobile)",
                    "Pakistan (Jazz)",
                    "Pakistan (Telenor)",
                    "Pakistan (Zong)",
                    "Poland (Mobile Vikings)",
                    "Qatar (Ooredoo)",
                    "Romania (Vodafone)",
                    "Russia (Beeline)",
                    "Russia (Rostelecom)",
                    "South Africa (MTN)",
                    "South Africa (TruTeq)",
                    "South Africa (CellC)",
                    "South Africa (Telekom)",
                    "South Africa (VodaCom)",
                    "South Africa (Virgin Mobile)",
                    "Sri Lanka (Mobitel)",
                    "Sri Lanka (Dialog)",
                    "Thailand (Ais)",
                    "Thailand (DTAC Happy)",
                    "Thailand (TrueCorp)",
                    "Uganda (Orange)",
                    "Ukraine (MTS)",
                    "United Kingdom(Globul)",
                    "United States (Virgin Mobile)",
                    "United States(Telekom)",
                    "Uzbekistan (Ucell)",
                    "Zimbabwe (EcoNet)",
                    "Zimbabwe (NetOne)",
                    "Zimbabwe (TeleCel)",
            };
}